name = "ecv-shortener"
main = "functions/[[path]].ts"
compatibility_date = "2024-11-01"

# Local / default
[vars]
PUBLIC_HOST = "localhost:8788"
ADMIN_HOST  = "admin.localhost:8788"
DEV_LOGIN_ENABLED = true

[[kv_namespaces]]
binding = "LINKS"
id = "dev-links"
preview_id = "dev-links-preview"

# Producción
[env.production.vars]
PUBLIC_HOST = "ecv.lat"
ADMIN_HOST  = "admin.ecv.lat"
DEV_LOGIN_ENABLED = false

[[env.production.kv_namespaces]]
binding = "LINKS"
id = "e67b6d3abe234a708e91d8486ae3af63"
