name: Preview (Cloudflare Pages)

on:
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  pull-requests: write

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build web
        run: pnpm --filter @ecv/web build

      # (Opcional) Crear namespaces KV si no existen (idempotente)
      - name: Ensure KV namespaces
        id: kv
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: |
            kv namespace create ecv_links_preview --json
      - name: Deploy Preview to Cloudflare Pages
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          # Usa wrangler para subir directorio + Functions
          command: pages deploy ./apps/web/dist --project-name=${{ secrets.PAGES_PROJECT_NAME }}

      - name: Comment Preview URL
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const url = core.getInput('url') || '${{ steps.deploy.outputs.deployment-url }}';
            const alias = '${{ steps.deploy.outputs.pages-deployment-alias-url }}';
            const body = `🚀 Preview desplegado:
- URL: ${url}
- Alias: ${alias || 'N/A'}`
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body
            });
